
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/STARTER-team03
owner: ucsb-cs156-f24
repo_name: STARTER-team03
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-updateNode","number":15,"title":"pc - update from github.com/ucsb-cs156/template-spring-react","url":"https://github.com/ucsb-cs156-f24/STARTER-team03/pull/15"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-pitest-param","number":14,"title":"pc - update pom.xml for partial pitest runs","url":"https://github.com/ucsb-cs156-f24/STARTER-team03/pull/14"},{"author":{"id":"MDQ6VXNlcjE2Mzg3MjY0","is_bot":false,"login":"TheNewJavaman","name":"Gabriel Pizarro"},"headRefName":"frontend-package-audit","number":4,"title":"Audit Frontend Packages","url":"https://github.com/ucsb-cs156-f24/STARTER-team03/pull/4"}]
