
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/STARTER-team02
owner: ucsb-cs156-f24
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-bump-body-parser","number":149,"title":"Bump body-parser and express in /frontend","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/149"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-bump-storybook","number":148,"title":"pc - update storybook version","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/148"},{"author":{"is_bot":true,"login":"app/dependabot"},"headRefName":"dependabot/npm_and_yarn/frontend/multi-6b7e5c81f3","number":87,"title":"Bump body-parser and express in /frontend","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/87"},{"author":{"is_bot":true,"login":"app/dependabot"},"headRefName":"dependabot/npm_and_yarn/frontend/rollup-2.79.2","number":86,"title":"Bump rollup from 2.79.1 to 2.79.2 in /frontend","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/86"}]
