
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/STARTER-team02
owner: ucsb-cs156-f24
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMTk5MDg4","is_bot":false,"login":"ahsun-tariq","name":"Ahsun Tariq"},"headRefName":"ahsun-w82-track-unassigned-issues","number":216,"title":"Ahsun w82 track unassigned issues","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/216"}]
