
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/STARTER-team02
owner: ucsb-cs156-f24
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-dj-datesUpdate","number":22,"title":"fixed error preventing UCSBDates from posting","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/22"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-suppressAnnotationProcessingWarning","number":21,"title":"pc - explicitly enable annotation processing","url":"https://github.com/ucsb-cs156-f24/STARTER-team02/pull/21"}]
